export const GD_RECEIVE_GAME_HEADER = 'GD_RECEIVE_GAME_HEADER'
export const GD_RESET_GAME_HEADER = 'GD_RESET_GAME_HEADER'

export const GD_RECEIVE_HOME_PLAYERS = 'GD_RECEIVE_HOME_PLAYERS'
export const GD_RESET_HOME_PLAYERS = 'GD_RESET_HOME_PLAYERS'

export const GD_RECEIVE_HOST_PLAYERS = 'GD_RECEIVE_HOST_PLAYERS'
export const GD_RESET_HOST_PLAYERS = 'GD_RESET_HOST_PLAYERS'

export const GD_RECEIVE_EVENTS = 'GD_RECEIVE_EVENTS'
export const GD_RESET_EVENTS = 'GD_RESET_EVENTS'