export const RECEIVE_MY_TEAM = 'RECEIVE_MY_TEAM';

export const RECEIVE_MY_TEAM_APPLICATION = 'RECEIVE_MY_TEAM_APPLICATION';

export const RECEIVE_MY_PLAYERS = 'RECEIVE_MY_PLAYERS';
export const RECEIVE_NEW_PLAYER = 'RECEIVE_NEW_PLAYER';
export const RECEIVE_UPDATED_PLAYER = 'RECEIVE_UPDATED_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const RECEIVE_PLAYER_FORM_MSG = 'RECEIVE_PLAYER_FORM_MSG';
export const RESET_PLAYER_FORM_MSG = 'RESET_PLAYER_FORM_MSG';

export const IS_FETCHING_TEAM = 'IS_FETCHING_TEAM';

export const RECEIVE_MY_GAMES_AS_REFEREE = 'RECEIVE_MY_GAMES_AS_REFEREE';
export const RECEIVE_MY_GAMES_TO_PLAY = 'RECEIVE_MY_GAMES_TO_PLAY';