export const RECEIVE_LOGGED_USER = 'RECEIVE_LOGGED_USER';
export const IS_FETCHING_USER = 'IS_FETCHING_USER';
export const RECEIVE_USER_LOGIN_MSG = 'RECEIVE_USER_LOGIN_MSG';
export const RESET_USER_LOGIN_MSG = 'RESET_USER_LOGIN_MSG';